config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '/admin' do
    resources :books
    resources :languages
    resources :translations
    resources :users
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/translation.rb
class Translation < ApplicationRecord
  belongs_to :book
  belongs_to :language

  validates :title, :isbn_13, :isbn_10, uniqueness: true
  validates :cover_image_url, format: {
      with: %r{\.(gif|jpg|jpeg|png)\Z}i,
      message: 'must be a URL for GIF, JPG/JPEG, or PNG image.'
  }

end

app/controllers/translations_controller.rb
class TranslationsController < AdminController
  before_action :set_translation, only: [:show, :edit, :update, :destroy]

  # GET /translations
  # GET /translations.json
  def index
    @translations = Translation.all
  end

  # GET /translations/1
  # GET /translations/1.json
  def show
  end

  # GET /translations/new
  def new
    @translation = Translation.new
  end

  # GET /translations/1/edit
  def edit
  end

  # POST /translations
  # POST /translations.json
  def create
    @translation = Translation.new(translation_params)

    respond_to do |format|
      if @translation.save
        format.html { redirect_to translations_url, notice: 'Translation was successfully created.' }
        format.json { render :show, status: :created, location: @translation }
      else
        format.html { render :new }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /translations/1
  # PATCH/PUT /translations/1.json
  def update
    respond_to do |format|
      if @translation.update(translation_params)
        format.html { redirect_to translations_url, notice: 'Translation was successfully updated.' }
        format.json { render :show, status: :ok, location: @translation }
      else
        format.html { render :edit }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translations/1
  # DELETE /translations/1.json
  def destroy
    @translation.destroy
    respond_to do |format|
      format.html { redirect_to translations_url, notice: 'Translation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_translation
      @translation = Translation.find(params[:id])
    end

    # Whitelist params
    def translation_params
      params.require(:translation).permit(:book_id, :language_id, :title, :cover_image_url, :publisher, :isbn_13,
                                          :isbn_10, :translator)
    end
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/translations/_form.html.erb
<%= form_for translation, html: {class: 'form-horizontal'} do |f| %>

    <% if translation.errors.any? %>
        <div class="alert alert-warning" role="alert">Invalid entries:
          <ul>
            <% translation.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :book_id, class: 'control-label col-md-2 col-sm-1' %>
      <div class="col-md-8 col-sm-10">
        <%= f.select :book_id, Book.all.collect { |book| [book.title, book.id] },
                     {prompt: 'Select a book'}, {class: 'form-control'} %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :language_id, class: 'control-label col-md-2 col-sm-1' %>
      <div class="col-md-8 col-sm-10">
        <%= f.select :language_id, Language.all.collect { |lang| [lang.name, lang.id] },
                     {prompt: 'Select a language'}, {class: 'form-control'} %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label 'Translated title', class: 'control-label col-md-2 col-sm-1' %>
      <div class="col-md-8 col-sm-10">
        <%= f.text_field :title, class: 'form-control', placeholder: 'Enter translated title' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label 'Image', class: 'control-label col-md-2 col-sm-1' %>
      <div class="col-md-8 col-sm-10">
        <%= f.text_field :cover_image_url, class: 'form-control', placeholder: 'Enter image url' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :publisher, class: 'control-label col-md-2 col-sm-1' %>
      <div class="col-md-8 col-sm-10">
        <%= f.text_field :publisher, class: 'form-control', placeholder: 'Enter publisher' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :translator, class: 'control-label col-md-2 col-sm-1' %>
      <div class="col-md-8 col-sm-10">
        <%= f.text_field :translator, class: 'form-control', placeholder: 'Enter translator' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :isbn_13, class: 'control-label col-md-2 col-sm-1' %>
      <div class="col-md-8 col-sm-10">
        <%= f.text_field :isbn_13, class: 'form-control', placeholder: 'Enter ISBN-13 #' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :isbn_10, class: 'control-label col-md-2 col-sm-1' %>
      <div class="col-md-8 col-sm-10">
        <%= f.text_field :isbn_10, class: 'form-control', placeholder: 'Enter ISBN-10 #' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-3 col-md-offset-2 col-xs-8 col-xs-offset-2">
        <%= f.submit class: 'btn btn-primary form-control' %>
      </div>
    </div>

<% end %>

app/views/translations/edit.html.erb
<div class="container-fluid col-md-8 col-md-offset-2 admin-form">
  <div class="panel panel-primary">

    <div class="panel-heading">
      <h1 class="panel-title">Edit translation</h1>
    </div>

    <div class="panel-body admin-form-fields">

      <%= render 'form', translation: @translation %>

    </div>
  </div>
</div>

app/views/translations/index.html.erb
<%= render 'shared/index_alerts' %>

<div class="container-fluid col-md-offset-1 col-md-10">
  <h1 class="sr-only">Translations</h1>
  <div class="row">

    <table class="table table-bordered">
      <thead>
      <tr>
        <th></th>
        <th>Cover</th>
        <th>Book</th>
        <th>Language</th>
        <th>Translated Title</th>
        <th>Publisher</th>
        <th>Translator</th>
        <th>ISBN-13</th>
        <th>ISBN-10</th>
      </tr>
      </thead>

      <tbody>
      <% @translations.each do |translation| %>
          <tr class="translation">
          <tr>
            <td>
              <%= link_to edit_translation_path(translation) do %>
                  <span class="glyphicon glyphicon-pencil"></span>
              <% end %>
              &nbsp;
              <%= link_to translation, method: :delete, data: {confirm: 'Are you sure?'} do %>
                  <span class="glyphicon glyphicon-remove"></span>
              <% end %>
            </td>
            <td><%= image_tag(translation.cover_image_url, size: '45x75') %></td>
            <td><%= translation.book.title %></td>
            <td><%= translation.language.name %></td>
            <td><%= translation.title %></td>
            <td><%= translation.publisher %></td>
            <td><%= translation.translator %></td>
            <td><%= translation.isbn_13 %></td>
            <td><%= translation.isbn_10 %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

  </div>
  <div class="row">
    <%= link_to 'New Translation', new_translation_path, class: 'btn btn-info', role: 'button' %>
  </div>
</div>

app/views/translations/new.html.erb
<div class="container-fluid col-md-8 col-md-offset-2 admin-form">
  <div class="panel panel-primary">

    <div class="panel-heading">
      <h1 class="panel-title">New translation</h1>
    </div>

    <div class="panel-body admin-form-fields">

      <%= render 'form', translation: @translation %>

    </div>
  </div>
</div>

app/views/translations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @translation.book.title %>
</p>

<p>
  <strong>Language:</strong>
  <%= @translation.language.name %>
</p>

<p>
  <strong>Translated title:</strong>
  <%= @translation.title %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @translation.publisher %>
</p>

<p>
  <strong>Translator:</strong>
  <%= @translation.translator %>
</p>

<p>
  <strong>ISBN-13:</strong>
  <%= @translation.isbn_13 %>
</p>

<p>
  <strong>ISBN-10:</strong>
  <%= @translation.isbn_10 %>
</p>

<p>
  <strong>Foreign cover image:</strong>
  <br>
  <br>
  <%= image_tag(@translation.cover_image_url, size: '150x200') %>
</p>

<%= link_to 'Edit', edit_translation_path(@translation) %> |
<%= link_to 'Back', translations_path %>