config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '/admin' do
    resources :books
    resources :languages
    resources :translations
    resources :users
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :translations
  before_destroy :ensure_not_referenced

  validates :name, :local_name, :slug, presence: true
  validates :name, :local_name, :slug, uniqueness: true

  def to_param
    slug
  end

  def ensure_not_referenced
    unless translations.empty?
      errors.add(:base, 'Language references translations')
      throw :abort
    end
  end
end

app/controllers/languages_controller.rb
class LanguagesController < AdminController
  before_action :set_language, only: [:show, :edit, :update, :destroy]

  # GET /languages
  # GET /languages.json
  def index
    @languages = Language.all
  end

  # GET /languages/slug
  # GET /languages/slug.json
  def show
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/slug/edit
  def edit
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to languages_url, notice: 'Language was successfully created.' }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/slug
  # PATCH/PUT /languages/slug.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to languages_url, notice: 'Language was successfully updated.' }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/slug
  # DELETE /languages/slug.json
  def destroy
    @language.destroy
    respond_to do |format|
      if @language.destroyed?
        format.html { redirect_to languages_url, notice: 'Language was successfully deleted.' }
        format.json { head :no_content }
      else
        format.html { redirect_to languages_url, alert: 'Language could not be removed. Make sure it is not being used
          elsewhere (e.g., if there is a translation to/from this language, the language cannot be removed).' }
        format.json { render json: @language.errors, status: :conflict }
      end
    end
  end

  private
    def set_language
      @language = Language.find_by_slug(params[:id])
    end

    # Whitelist params
    def language_params
      params.require(:language).permit(:name, :local_name, :slug)
    end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_form.html.erb
<%= form_for language, html: {class: 'form-horizontal'} do |f| %>

    <% if language.errors.any? %>
        <div class="alert alert-warning" role="alert">Invalid entries:
          <ul>
            <% language.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, class: 'control-label col-md-2 col-sm-1' %>
      <div class="col-md-8 col-sm-10">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Enter name' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label 'Translated name', class: 'control-label col-md-2 col-sm-1' %>
      <div class="col-md-8 col-sm-10">
        <%= f.text_field :local_name, class: 'form-control', placeholder: 'Enter translated form of language' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :slug, class: 'control-label col-md-2 col-sm-1' %>
      <div class="col-md-8 col-sm-10">
        <%= f.text_field :slug, class: 'form-control', placeholder: 'Enter slug' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-3 col-md-offset-2 col-xs-8 col-xs-offset-2">
        <%= f.submit class: 'btn btn-primary form-control' %>
      </div>
    </div>

<% end %>

app/views/languages/edit.html.erb
<div class="container-fluid col-md-8 col-md-offset-2 admin-form">
  <div class="panel panel-primary">

    <div class="panel-heading">
      <h1 class="panel-title">Edit language</h1>
    </div>

    <div class="panel-body admin-form-fields">

      <%= render 'form', language: @language %>

    </div>
  </div>
</div>

app/views/languages/index.html.erb
<%= render 'shared/index_alerts' %>

<div class="container-fluid col-md-offset-1 col-md-10">
  <h1 class="sr-only">Languages</h1>
  <div class="row">

    <table class="table table-bordered">
      <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Translated name</th>
        <th>Slug</th>
      </tr>
      </thead>

      <tbody>
      <% @languages.each do |language| %>
          <tr class="language">
          <tr>
            <td>
              <%= link_to edit_language_path(language) do %>
                  <span class="glyphicon glyphicon-pencil"></span>
              <% end %>
              &nbsp;
              <%= link_to language, method: :delete, data: {confirm: 'Are you sure?'} do %>
                  <span class="glyphicon glyphicon-remove"></span>
              <% end %>
            </td>
            <td><%= language.name %></td>
            <td><%= language.local_name %></td>
            <td><%= language.slug %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

  </div>
  <div class="row">
    <%= link_to 'New Language', new_language_path, class: 'btn btn-info', role: 'button' %>
  </div>
</div>

app/views/languages/new.html.erb
<div class="container-fluid col-md-8 col-md-offset-2 admin-form">
  <div class="panel panel-primary">

    <div class="panel-heading">
      <h1 class="panel-title">New language</h1>
    </div>

    <div class="panel-body admin-form-fields">

      <%= render 'form', language: @language %>

    </div>
  </div>
</div>

app/views/languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @language.name %>
</p>

<p>
  <strong>Local name:</strong>
  <%= @language.local_name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @language.slug %>
</p>

<%= link_to 'Edit', edit_language_path(@language) %> |
<%= link_to 'Back', languages_path %>