config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '/admin' do
    resources :books
    resources :languages
    resources :translations
    resources :users
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ayn Rand Translations</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="<%= controller.controller_name %>">
<nav class="navbar navbar-default navbar-inverse" role="navigation">
  <div class="container-fluid" id="navfluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigationbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <p class="navbar-text <%= 'active' if current_page?(admin_url) %>">Admin</p>
    </div>
    <div class="collapse navbar-collapse" id="navigationbar">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(books_path) %>">
          <%= link_to 'Books', books_path %>
        </li>
        <li class="<%= 'active' if current_page?(languages_path) %>">
          <%= link_to 'Languages', languages_path %>
        </li>
        <li class="<%= 'active' if current_page?(translations_path) %>">
          <%= link_to 'Translations', translations_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if current_page?(users_path) %>">
          <%= link_to 'Admins', users_path %>
        </li>
        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div id="header">
  <div id="main">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ayn Rand Translations</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

  <body class="<%= controller.controller_name %>">
    <div id="header">
      <div id="main">
        <%= yield %>
      </div>
    </div>
  </body>
</html>